version: '3'
services:
  web:
    build: 
      context: ./Financiera
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Financiera:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: financiera-web


    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 