# Generated by Django 5.0 on 2024-09-25 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Privado', 'Privado'), ('Gobierno', 'Gobierno')], max_length=20)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='La edad debe ser mayor o igual a 1.'), django.core.validators.MaxValueValidator(99, message='La edad debe ser menor o igual a 99.')])),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_habitacion', models.TextField(blank=True, null=True)),
                ('correo_electronico', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='Ingresa un correo electrónico válido.')])),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_persona', models.CharField(blank=True, choices=[('Natural', 'Natural'), ('Jurídico', 'Jurídico')], max_length=20, null=True)),
                ('banco_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_credito', models.TextField()),
                ('pago_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('tipo_credito', models.CharField(blank=True, choices=[('Automotriz', 'Automotriz'), ('Hipotecario', 'Hipotecario'), ('Comercial', 'Comercial')], max_length=20, null=True)),
                ('banco_otorgante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.banco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.cliente')),
            ],
        ),
    ]
